/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Buoi5;

import java.math.BigInteger;
import java.security.SecureRandom;

/**
 *
 * @author Administrator
 */
public class frm_Alice extends javax.swing.JFrame {

    private BigInteger p = new BigInteger("353"); // số nguyên tố
    private BigInteger g = new BigInteger("3");   // cơ số g
    private BigInteger a;          // private key Alice
    private BigInteger A;          // public key Alice (A = g^a mod p)
    private BigInteger B;          // public key Bob lấy từ Bob
    private BigInteger sharedSecret;
    
    // Static reference để trao đổi keys với Bob
    private static frm_Bob bobInstance = null;
    private static frm_Alice aliceInstance = null;

    public frm_Alice() {
        initComponents();
    }
    
    // Set reference đến Bob form
    public static void setBobInstance(frm_Bob bob) {
        bobInstance = bob;
    }
    
    // Lấy reference đến Bob form
    public static frm_Bob getBobInstance() {
        return bobInstance;
    }
    
    // Set reference đến Alice form (chính nó)
    public static void setAliceInstance(frm_Alice alice) {
        aliceInstance = alice;
    }
    
    // Lấy reference đến Alice form
    public static frm_Alice getAliceInstance() {
        return aliceInstance;
    }
    
    // Phương thức để tự động kết nối với Bob form
    public void connectToBobForm() {
        frm_Bob bob = frm_Bob.getBobInstance();
        if(bob != null) {
            frm_Alice.setBobInstance(bob);
            frm_Bob.setAliceInstance(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Encrypt secret key");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encryptsecretkey(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Run encrypt/decrypt form");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_runEncryptDecryptForm(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Alice key generate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alicekey(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jLabel1.setText("Alice Key");

        jLabel2.setText("Bob Key");

        jLabel3.setText("Shared Secret");

        jLabel4.setText("enccypt shared secret");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Bob key display");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bobkey(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Alice Form");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Make secret key");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_makesecretkey(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(89, 89, 89)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(53, 53, 53))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5))))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_encryptsecretkey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encryptsecretkey
        // TODO add your handling code here:
        if(sharedSecret == null) {
            jTextArea4.setText("Chưa tạo secret key!");
            return;
        }
        byte[] keyBytes = sharedSecret.toByteArray();
        jTextArea4.setText(CryptoUtil.toHexString(keyBytes));
    }//GEN-LAST:event_btn_encryptsecretkey

    private void btn_runEncryptDecryptForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_runEncryptDecryptForm
        // TODO add your handling code here:
        if(sharedSecret == null) {
            jTextArea4.setText("Chưa có shared secret!");
            return;
        }
        frm_DESCS encForm = new frm_DESCS(sharedSecret);
        encForm.setVisible(true);
    }//GEN-LAST:event_btn_runEncryptDecryptForm

    private void btn_alicekey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alicekey
        // TODO add your handling code here:
        try {
            SecureRandom random = new SecureRandom();
            // Tạo private key a trong khoảng [1, p-2]
            a = new BigInteger(p.bitLength()-1, random)
                .mod(p.subtract(BigInteger.TWO))
                .add(BigInteger.ONE);
            // Tính public key A = g^a mod p
            A = g.modPow(a, p);
            jTextArea1.setText(A.toString()); // Hiển thị public key
            
            // Đảm bảo kết nối với Bob form trước khi gửi key
            connectToBobForm();
            frm_Bob bob = frm_Bob.getBobInstance();
            
            // Tự động gửi public key cho Bob nếu có
            if(bob != null && A != null) {
                bob.setAliceKey(A);
            }
        } catch(Exception e) {
            jTextArea1.setText("Lỗi tạo key!");
        }
    }//GEN-LAST:event_btn_alicekey

    private void btn_bobkey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bobkey
        // TODO add your handling code here:
        // Đảm bảo kết nối với Bob form
        connectToBobForm();
        frm_Bob bob = frm_Bob.getBobInstance();
        
        // Lấy Bob public key từ Bob form nếu có
        if(bob != null) {
            BigInteger bobPubKey = bob.getBobPublicKey();
            if(bobPubKey != null) {
                B = bobPubKey;
                jTextArea2.setText(B.toString());
            } else {
                jTextArea2.setText("Bob chưa tạo public key!");
            }
        } else {
            jTextArea2.setText(B != null ? B.toString() : "Chưa kết nối với Bob form!");
        }
    }//GEN-LAST:event_btn_bobkey

    private void btn_makesecretkey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_makesecretkey
        // TODO add your handling code here:
        try {
            if (a == null) {
                jTextArea3.setText("Chưa tạo Alice private key!");
                return;
            }
            if (B == null) {
                jTextArea3.setText("Chưa có Bob public key!");
                return;
            }
            // Tính shared secret: K = B^a mod p
            sharedSecret = B.modPow(a, p);
            jTextArea3.setText(sharedSecret.toString());
        } catch(Exception e) {
            jTextArea3.setText("Lỗi tính secret key!");
        }
    }//GEN-LAST:event_btn_makesecretkey

    // Lấy Bob public key từ frm_Bob
    public void setBobPublicKey(BigInteger bobPublicKey) {
        this.B = bobPublicKey;
    }
    
    // Trả về Alice public key để gửi cho Bob
    public BigInteger getAlicePublicKey() {
        return A;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Alice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_Alice alice = new frm_Alice();
                frm_Alice.setAliceInstance(alice);
                alice.setVisible(true);
                // Tự động kết nối với Bob form nếu đã có
                alice.connectToBobForm();
                // Nếu Bob form đã tồn tại, cập nhật reference của Bob form
                frm_Bob bob = frm_Bob.getBobInstance();
                if(bob != null) {
                    bob.connectToAliceForm();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
