/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Buoi5;

import java.math.BigInteger;
import java.security.SecureRandom;

/**
 *
 * @author Administrator
 */
public class frm_Bob extends javax.swing.JFrame {

    private BigInteger p; // prime
    private BigInteger g; // generator
    private BigInteger b; // Bob private key
    private BigInteger B; // Bob public key
    private BigInteger A; // Alice public key
    private BigInteger secretKey; // shared secret

    private SecureRandom random = new SecureRandom();
    
    // Static reference để trao đổi keys với Alice
    private static frm_Alice aliceInstance = null;
    private static frm_Bob bobInstance = null;

    public frm_Bob() {
        initComponents();
        // Khởi tạo p, g giống Alice
            p = new BigInteger("353");
            g = new BigInteger("3");

    }
    
    // Set reference đến Alice form
    public static void setAliceInstance(frm_Alice alice) {
        aliceInstance = alice;
    }
    
    // Lấy reference đến Alice form
    public static frm_Alice getAliceInstance() {
        return aliceInstance;
    }
    
    // Set reference đến Bob form (chính nó)
    public static void setBobInstance(frm_Bob bob) {
        bobInstance = bob;
    }
    
    // Lấy reference đến Bob form
    public static frm_Bob getBobInstance() {
        return bobInstance;
    }
    
    // Phương thức để tự động kết nối với Alice form
    public void connectToAliceForm() {
        frm_Alice alice = frm_Alice.getAliceInstance();
        if(alice != null) {
            frm_Bob.setAliceInstance(alice);
            frm_Alice.setBobInstance(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Encrypt secret key");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4btn_encryptsecretkey(evt);
            }
        });

        jLabel1.setText("Bob Key");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Alice Key");

        jLabel3.setText("Shared Secret");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Run encrypt/decrypt form");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5btn_runEncryptDecryptForm(evt);
            }
        });

        jLabel4.setText("enccypt shared secret");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Alice key display");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2btn_alicekey(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Bob Form");

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Bob key generate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6btn_bobkey(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Make secret key");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3btn_makesecretkey(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4btn_encryptsecretkey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4btn_encryptsecretkey
        // TODO add your handling code here:
        if(secretKey == null) {
            jTextArea4.setText("Chưa tạo secret key!");
            return;
        }
        byte[] keyBytes = secretKey.toByteArray();
        jTextArea4.setText(CryptoUtil.toHexString(keyBytes));
    }//GEN-LAST:event_jButton4btn_encryptsecretkey

    private void jButton5btn_runEncryptDecryptForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5btn_runEncryptDecryptForm
        // TODO add your handling code here:
        if(secretKey == null) {
            jTextArea4.setText("Chưa có secret key để mã hóa!");
            return;
        }
        // Mở form DES/CS dùng secret key
        frm_DESCS desForm = new frm_DESCS(secretKey);
        desForm.setVisible(true);
    }//GEN-LAST:event_jButton5btn_runEncryptDecryptForm

    private void jButton2btn_alicekey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2btn_alicekey
        // TODO add your handling code here:
        // Đảm bảo kết nối với Alice form
        connectToAliceForm();
        frm_Alice alice = frm_Alice.getAliceInstance();
        
        // Lấy Alice public key từ Alice form nếu có
        if(alice != null) {
            BigInteger alicePubKey = alice.getAlicePublicKey();
            if(alicePubKey != null) {
                A = alicePubKey;
                jTextArea2.setText(A.toString());
            } else {
                jTextArea2.setText("Alice chưa tạo public key!");
            }
        } else {
            if(A != null) {
                jTextArea2.setText(A.toString());
            } else {
                jTextArea2.setText("Chưa kết nối với Alice form!");
            }
        }
    }//GEN-LAST:event_jButton2btn_alicekey

    private void jButton6btn_bobkey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6btn_bobkey
        // TODO add your handling code here:
        try {
            b = new BigInteger(p.bitLength()-1, random)
                .mod(p.subtract(BigInteger.TWO))
                .add(BigInteger.ONE);
            B = g.modPow(b, p);
            jTextArea1.setText(B.toString());
            
            // Đảm bảo kết nối với Alice form trước khi gửi key
            connectToAliceForm();
            frm_Alice alice = frm_Alice.getAliceInstance();
            
            // Tự động gửi public key cho Alice nếu có
            if(alice != null && B != null) {
                alice.setBobPublicKey(B);
            }
        } catch(Exception e) {
            jTextArea1.setText("Lỗi tạo key!");
        }
    }//GEN-LAST:event_jButton6btn_bobkey

    private void jButton3btn_makesecretkey(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3btn_makesecretkey
        // TODO add your handling code here:
        try {
            if(b == null) {
                jTextArea3.setText("Chưa tạo Bob private key!");
                return;
            }
            if(A == null) {
                jTextArea3.setText("Chưa có Alice public key!");
                return;
            }
            // Tính shared secret: K = A^b mod p
            secretKey = A.modPow(b, p);
            jTextArea3.setText(secretKey.toString());
        } catch(Exception e) {
            jTextArea3.setText("Lỗi tính secret key!");
        }
    }//GEN-LAST:event_jButton3btn_makesecretkey

    // Setter để nhận Alice public key
    public void setAliceKey(BigInteger alicePublicKey) {
        this.A = alicePublicKey;
        jTextArea2.setText(A.toString()); // hiển thị Alice key
    }
    
    public BigInteger getBobPublicKey() {
        return B;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Bob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_Bob bob = new frm_Bob();
                frm_Bob.setBobInstance(bob);
                bob.setVisible(true);
                // Tự động kết nối với Alice form nếu đã có
                bob.connectToAliceForm();
                // Nếu Alice form đã tồn tại, cập nhật reference của Alice form
                frm_Alice alice = frm_Alice.getAliceInstance();
                if(alice != null) {
                    alice.connectToBobForm();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
